{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-08-05 09:23:31,194+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"Invalid header value b'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiZDoxIiwiZDoyIiwieDowIiwieDoxIiwieDoyIl0sImF0X2hhc2giOiJnQUFBQUFCb2tZYTI2MkdPWEs0eXpqYloyLTlkb2FwazZBVk9BWTg1M0t3anVCN2N6SzdJYmFyakVXX01ad1M1MGxqVUVwRVpCcUZjNk1laVc4WEFIdFFMM2NKM1YteXcwWnJfSlIxekFKOVhZM2dnMUV1M05OND0iLCJkaXNwbGF5X25hbWUiOiIiLCJvbXMiOiJLMSIsImhzbV9rZXkiOiI1ZWUxMmUxN2I3NzExMGQ2MmZjZTZlNGU3YTA3YjFjMzU1MGNmNTYyMjZiMDZkYzU2NjUwYTE2ZCIsImlzRGRwaUVuYWJsZWQiOiJOIiwiaXNNdGZFbmFibGVkIjoiTiIsImZ5X2lkIjoiWFIwNDc1MCIsImFwcFR5cGUiOjEwMCwiZXhwIjoxNzU0NDQwMjAwLCJpYXQiOjE3NTQzNjc2NzAsImlzcyI6ImFwaS5meWVycy5pbiIsIm5iZiI6MTc1NDM2NzY3MCwic3ViIjoiYWNjZXNzX3Rva2VuIn0.R81zSKEwamwju6J8vBSnrjASRDY1RpAiUDQeT8BQzh4\\n'","timestamp":"2025-08-05 10:12:16,857+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 63, in symbol_to_hsmtoken\n    response = requests.post(\n               ^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\adapters.py\", line 486, in send\n    resp = conn.urlopen(\n           ^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    response = self._make_request(\n               ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 493, in _make_request\n    conn.request(\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connection.py\", line 493, in request\n    self.putheader(header, value)\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connection.py\", line 407, in putheader\n    super().putheader(header, *values)\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\http\\client.py\", line 1297, in putheader\n    raise ValueError('Invalid header value %r' % (values[i],))\nValueError: Invalid header value b'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiZDoxIiwiZDoyIiwieDowIiwieDoxIiwieDoyIl0sImF0X2hhc2giOiJnQUFBQUFCb2tZYTI2MkdPWEs0eXpqYloyLTlkb2FwazZBVk9BWTg1M0t3anVCN2N6SzdJYmFyakVXX01ad1M1MGxqVUVwRVpCcUZjNk1laVc4WEFIdFFMM2NKM1YteXcwWnJfSlIxekFKOVhZM2dnMUV1M05OND0iLCJkaXNwbGF5X25hbWUiOiIiLCJvbXMiOiJLMSIsImhzbV9rZXkiOiI1ZWUxMmUxN2I3NzExMGQ2MmZjZTZlNGU3YTA3YjFjMzU1MGNmNTYyMjZiMDZkYzU2NjUwYTE2ZCIsImlzRGRwaUVuYWJsZWQiOiJOIiwiaXNNdGZFbmFibGVkIjoiTiIsImZ5X2lkIjoiWFIwNDc1MCIsImFwcFR5cGUiOjEwMCwiZXhwIjoxNzU0NDQwMjAwLCJpYXQiOjE3NTQzNjc2NzAsImlzcyI6ImFwaS5meWVycy5pbiIsIm5iZiI6MTc1NDM2NzY3MCwic3ViIjoiYWNjZXNzX3Rva2VuIn0.R81zSKEwamwju6J8vBSnrjASRDY1RpAiUDQeT8BQzh4\\n'","exception_name":"ValueError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-08-05 10:12:17,063+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"Invalid header value b'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiZDoxIiwiZDoyIiwieDowIiwieDoxIiwieDoyIl0sImF0X2hhc2giOiJnQUFBQUFCb2tZYTI2MkdPWEs0eXpqYloyLTlkb2FwazZBVk9BWTg1M0t3anVCN2N6SzdJYmFyakVXX01ad1M1MGxqVUVwRVpCcUZjNk1laVc4WEFIdFFMM2NKM1YteXcwWnJfSlIxekFKOVhZM2dnMUV1M05OND0iLCJkaXNwbGF5X25hbWUiOiIiLCJvbXMiOiJLMSIsImhzbV9rZXkiOiI1ZWUxMmUxN2I3NzExMGQ2MmZjZTZlNGU3YTA3YjFjMzU1MGNmNTYyMjZiMDZkYzU2NjUwYTE2ZCIsImlzRGRwaUVuYWJsZWQiOiJOIiwiaXNNdGZFbmFibGVkIjoiTiIsImZ5X2lkIjoiWFIwNDc1MCIsImFwcFR5cGUiOjEwMCwiZXhwIjoxNzU0NDQwMjAwLCJpYXQiOjE3NTQzNjc2NzAsImlzcyI6ImFwaS5meWVycy5pbiIsIm5iZiI6MTc1NDM2NzY3MCwic3ViIjoiYWNjZXNzX3Rva2VuIn0.R81zSKEwamwju6J8vBSnrjASRDY1RpAiUDQeT8BQzh4\\n'","timestamp":"2025-08-05 20:25:36,029+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 63, in symbol_to_hsmtoken\n    response = requests.post(\n               ^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\adapters.py\", line 486, in send\n    resp = conn.urlopen(\n           ^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    response = self._make_request(\n               ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 493, in _make_request\n    conn.request(\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connection.py\", line 493, in request\n    self.putheader(header, value)\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connection.py\", line 407, in putheader\n    super().putheader(header, *values)\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\http\\client.py\", line 1297, in putheader\n    raise ValueError('Invalid header value %r' % (values[i],))\nValueError: Invalid header value b'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiZDoxIiwiZDoyIiwieDowIiwieDoxIiwieDoyIl0sImF0X2hhc2giOiJnQUFBQUFCb2tZYTI2MkdPWEs0eXpqYloyLTlkb2FwazZBVk9BWTg1M0t3anVCN2N6SzdJYmFyakVXX01ad1M1MGxqVUVwRVpCcUZjNk1laVc4WEFIdFFMM2NKM1YteXcwWnJfSlIxekFKOVhZM2dnMUV1M05OND0iLCJkaXNwbGF5X25hbWUiOiIiLCJvbXMiOiJLMSIsImhzbV9rZXkiOiI1ZWUxMmUxN2I3NzExMGQ2MmZjZTZlNGU3YTA3YjFjMzU1MGNmNTYyMjZiMDZkYzU2NjUwYTE2ZCIsImlzRGRwaUVuYWJsZWQiOiJOIiwiaXNNdGZFbmFibGVkIjoiTiIsImZ5X2lkIjoiWFIwNDc1MCIsImFwcFR5cGUiOjEwMCwiZXhwIjoxNzU0NDQwMjAwLCJpYXQiOjE3NTQzNjc2NzAsImlzcyI6ImFwaS5meWVycy5pbiIsIm5iZiI6MTc1NDM2NzY3MCwic3ViIjoiYWNjZXNzX3Rva2VuIn0.R81zSKEwamwju6J8vBSnrjASRDY1RpAiUDQeT8BQzh4\\n'","exception_name":"ValueError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-08-05 20:25:36,035+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-08-07 09:20:50,529+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-08-07 09:24:34,129+0530","service":"FyersDataSocket"}
